apiVersion: v1
kind: Secret
metadata:
  name: kopiur-repository-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:I0x3A44wRMuPbtUS1Pw0G0wM0jHweOlZQvuTuVrkkjQ=,iv:70KPSgVaLtR3FnTdTW1jRVoADgi3mvzAWSdSnSVBUVc=,tag:NRiK+CNTrzGeMh5yIbDjfQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZxilCmot7GWcGRmRJbqY6RBLlCU=,iv:vbPLw8dImmTPqtpJ1bbWDMUFBjyoVxWXYaA6ezwmBS0=,tag:zf5UauzCudTaesLjwD6M+A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kLJ0u2fYnjp96SHSPZH08vpYQW77rPg/ilz37AOlwTilLZAkcleBbw==,iv:QuvS/I24uFojXY7WqxecVoiym39rNePhz0biYeRlg/Q=,tag:xP3KvUG+Vevo0+z/ojSxYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFxQldhbGpO
        U1dKd2hsMWpqMXF1TlhyWHMvSUs4b29IZ3Z5MnhlWklXcVd4ekFCa1FuWTJrZHFF
        dWZjUE9Yd1RDMWI1U2Z0M1RLYWphemdOMVBrOHFwUHBKTlRsUk5sK1NXSTU5bEFI
        M3hLQWJPeWJFNlRUKzhTdnlWSGhHN3YxeU9odHlzOFQ5dmI1OHlJb0s3VzV6bWtI
        NDRpQWxwNGJPdngwcGVUQ21oOWd4STlLN04zRGFMNkVZbStNRmZiZGgrRVpQbmFN
        a2lTSFkvOEFHWmJBVllUUFMwUXgrWXRGbFEzSzhyYXptTUUwK2F1NXJ2cmJBbm9U
        ZFh4RlBvb083WnFSaUJpU0dVZURxLzdvRUp0eXR3Q3piTWg4WWZoMnRZSzYvU0Y4
        WkJKRUR0Z294cTA2ZzZFcmw3SzBVejNDTVlHUy9kMkwwdzdpNDB0REVSZkRscnY3
        N3BOWUs0cTBDUFVvYjFHL1lyRlVLdDdZWWJqYk5FQ2ExdUJ0aVdVU1BaaE9qOFJO
        d1lEaE1sVkxjNkZ6Y0lPcEpPNy95cnY1clNUWEx4d01NM2NyNHl0YlRpa3JiSHU2
        VVcrNkxucnBDVzcxcUlQSmNTN3VjcnNUMUlTU3QvOGVRUGI4YUl6bGNWZTA0VEN0
        NU9CQW9jUE5OWDRmbmxKeUJvcFNnTlY1Unl3RllOeE44RXZRTjRzaHp6NzhGT2o0
        bWlZMThBeFo4OW1mRnAvSmM3eS93YXo0S1BheUVIa0ZJRWFuT2pJQkNTb1ROSm9U
        QlNyRFRxYXJsUnVPczVaZzZMQ213dm04YllDSDZhcTZwMitYaHBLSzRWSWZ0dkFa
        MTNBQ0NGTHJITFpGd1lDOE9wN09kQitCbUlBeVdkTlhiNmhBL2xRT2lLQ3RRSmp1
        M2Q2S1ZnTmMwbzl1aEJ3NVJ6WlUwUEVVRTQ4VXVrUWZpZnRyVThURFp0UmlQTURq
        T2VDL3ZibXJkTzI4cjBPa0M4eEI0WFRGT01VbWt3STdxb1gwSTVDMit1a2ZsRm9m
        NU9aQXE5NmtIYUlEdmliRWxpUW1URW8zcDQ3d1dTM2pnS2lucTJxTzFUZDJDZmIy
        WGp6Q25qWXRaMVFSd0tqa1ZZM3RyMHNRdXMrWkJtVWhWSGdtRkVSa1QvbTNDNm1E
        VVJFQ3h3MHZiakNBUnRwS0dzV0RFRkVGSC9QNjNzc1NnUHplSjVVYTlEbUFXc1ZK
        NGVxcW1peXNDYlhVQXQrR1Ewc1RQMHNPaHdOeERrdE0vVDlPeVNrZk1DMWVoaFkv
        TjdKbTVESmNzeW1jRElDUWZkdzdKT3lOL2E1N3licE5haFVPYjd2N0lJd3ZyK0pI
        YVU0dTNtc3VBUytrcGJWSGVuK0RrRWFzVGtndjdOUXVtTUw2Qk1uTUhDaEdJZmk0
        M3VCR1JaNTBMSUQwUHk0MmgzSzZ2bEpqanFnTEZPTDRHR2tWM1dGVGNHVUhiU1N6
        S1liMXRXemFQeEpjbVJRcVpYaW5BNHZOMzNGQTFvUkNmOXNQWnlwZG9xVklrZEFh
        YW9TY2tPMTRzYVRWQUhtSmNXUEpxNFpURkpaTGt0U01zMVl0UE9XNWljaHF6V2NQ
        RlJaR3JiWi90KzA4SG51UTFhenZwbjBjMDdzRjJQVTZ3VlVBQm1iYUE3aE9zR1lR
        cDNZZzBFKzhrMlpXOEhNeUdPZURpTERvYTFsbElvK2E1TnoxMDBFNHZmZlBiTWVi
        WnliNlNsS3UrR2lTdzAxZ3pMT01LWTNNQlFFZzQ4aVVadTg4ekdDT2ZxVmdsUm1q
        bHZnUDJCM042ZjFkTkpZbko2MnZWTm90L3h5Yk1MY1NhVnhwNzRJbmc3dEdBZVJa
        WVZoUVlKL0xLQXpYZm1pVjIxVnJ2dGZqbTBMMkxpTjJpYXhwYTN0dGdkeVVOUlVX
        c1FkN0t5bG5mWnptUnllMHE2eGhOd1ZSa1F4bVVvQks4NjNKWk1DL2pqRmFldwox
        M3NwQzVrVEFRQnhzMmZmNkk4NUVPVk9yeUw3cmN2NUUxSEpxQk1FaG04Ci0tLSAw
        SUpiVVZjRjFhNUdVU1ZDK1FiZytxY3BZVDQ0anhvWG5hUnZDNFJpWExZCmqX9H07
        dBshEXK7hCvMNeHtBEFMu78gb2sk5QtmTnIlTPRQLLF+1f/Td5YsDXe/GfNBZjsP
        fnzI1a52s7MJvLw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1q25jc4rp25dq0tpnc4vkwxr6ke6mqevjvcue3fcxv9292sxdvzzfz3n6k73rssk8zjap9c3nqtszxgaz27vm4qzlfzaampglkqf4e7h8rhqy8y09u357j5e35rsz8zxuwafuxr9rxe2qhkszal697e5tskjt0dphcctdm5c793yqpdh42uchnslllzetck9f9fdpkcgpcjfa52j7zuv40wsutgf2ad34vqy7pwzeg3nq0g248l45vsdxzprakzentq37d7p8nhft7j9tj99ccj04tqk38xclrht3pzekrhjpz66fz2q8ck36mjqsf5efz25ycgpz33ekkcvwvhasd5ruyyt8cez4prz8hk4pukd6xvmuzfezf08zngqgunzwepg5a5lj9nfhz5se565vexjz4k7tjzgzdlzyhj2a3vm8p42j3xvm4yxuk3qeh0x7756l9c7qxn5hs0wurl5ppp3z5svq68q5gtcp2vf3tux79z8225xx49enwtdj04vvcg0lgyddm3qm4ymudt7ggk9vc0n24zfewj4dceph7m9sa05vphajzrugj5y3mjy9umpshdue39n62fkmewy0zf9pd4atcfg3qd5e0dtleqq4s93d2mn589arwj3hqy5jp277pzxzvspz5kj5wcarkp6nzu2spdvjxwgvqvg2w3sw4de462u84tpgnfu6qvmrdzmafg26ewk9mj2ld02qmw2f97qex427s7tdfdk02cm9e7x5yqr9ktrn32pflc2vlunh4jayqn3atxnns3uu9u32k94eehvyjm2kxahr5yuy4yc054c2cnw4q9ensrqsqjy084r3rfzy7pjpesn3h9st397henyd5u46c434d74x0yq2f95ayjut2gte9mhffsgq3tmd2zzppatj9x6t7xcj43updyh2pg82keex90ykk9jzqlup83rd3z2fyenxxaqv9ud8ffamdfevdq843nzadn48ay0cswyt27cjepl4zprt3vfkmrdyy7y4zedrefe37fum39s8th6nk9h7ghvz8guvc7tp5c2eskly0w3ljksevvsaga4r9wgrqhrm3y8r5aq2h3cxka5knnpr8xvt5juudvqeuggd25sppz2v576rcfkpfy432ryvqj9uk6mvxzjywsxv4tahx62qjxqcxwuy9sscx48l9wtf67kax2s95latd22h0cvvgcyqkptrl7ekvcnfgnps3kst8re94sfpn7pzc74m5e3x8y480ty9j4tu5cax4xuujxt84l4s4f2h6pxn2zrh5juykjpcx3ftzfghx9w0mewxk0j4z3j8946qvqjn9wlw5jza4sa6kpcyyhlgyppnl39tyw6jgl6sj9epww4d9zyl5pwu59p0cmdhvqg54j2rvycvwcaq4qa5gqeynp83yf3awjkl3pqcfvr4gsy4d7x3sae72936za065kmwg864yx3c3pmlvhprqjl423tcshcvxtrnrza9z2znfvy0yk2rujp68wjuxxzkcs235lqp9yaqhuguanrt8xgsftdpvfg5jxvpet3qjpxz9gv3j548epx2yuqghhxqvm7hc2e782wfywhwnu5vp4emhglgnekz03p7awz0rqmmelpys2d6z7f2986zhwhacjt9pdx8ly5k4gk0r3qunsa52npm7ypq52h5s69ph3vdsupjacq6v2kx0f9x8zm3e0w0hsmwsu5z27q63985zdu3rgjcxur87wad3qyxntl45qa4dydtcayk7zna6tn307qmtwz4jhh7qz2sew5zgkdvlm4rsj0kye2uf0pmmy6tw75c90qtqytgk7sgnw845htwej8rrfa3qw7kta8j3pmhlfjka5nhq7g5sxw5u4cd98nr3rgmp6vgpcyrpkt29ufjuagkkzf5vv24svtvfy4y3luyud7uhktjvcthtrnz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-24T21:49:00Z"
  mac: ENC[AES256_GCM,data:+HSjoYH/ktxHtfd9V8C0xqCo+mYM4sMGDQDBesBbU/hTEjnfDN/cs+sHC34/6+8WNmd8FSvMDWfLq9foc+Zs+hy+4O0vM31kDMAmTRMCb00bXdp5/K/yCCAqW82RNnzGY0uTaI1ZsN50LWlanOeyBOjn3wJ+f5LMxRyhQTA9ifY=,iv:xlAUWNPJd3UuVvfy8V5R83k9oZR6awPpk77cz7QEZVM=,tag:drJIQa5MpGCnhfyGtq+UFw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
