#!/usr/bin/env bash
set -o errexit

INTIGRATION_DIR=$1
MANIFEST_NAME=$2

case $MANIFEST_NAME in
    "cilium")
        MANIFEST_DIR=$INTIGRATION_DIR/cni
        ;;
    "kubelet-csr-approver")
        MANIFEST_DIR=$INTIGRATION_DIR/kubelet-csr-approver
        ;;
    *)
        echo "Unknown $MANIFEST_NAME"
esac

rm -rf charts

echo "# This manifest was generated by automation. DO NOT EDIT." > $MANIFEST_DIR/$MANIFEST_NAME.yaml

echo "---" >> $MANIFEST_DIR/$MANIFEST_NAME.yaml

kustomize build \
  --enable-helm \
  --load-restrictor=LoadRestrictionsNone \
  . \
  >> $MANIFEST_DIR/$MANIFEST_NAME.yaml

rm -rf charts

prettier --config .ci/prettier/.prettierrc.yaml --write $MANIFEST_DIR/$MANIFEST_NAME.yaml
