version: v1alpha1 # Indicates the schema used to decode the contents.
debug: false # Enable verbose logging to the console.
persist: true
# Provides machine specific configuration options.
machine:
  type: controlplane # Defines the role of the machine within the cluster.
  token: ho6bzi.4laeze1du7vvrixf # The `token` is used by a machine to join the PKI of the cluster.
  # The root certificate authority of the PKI.
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJGVHBDZXpYbktqcXVCSUM0NloyQ25NQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTVNRGd4TnpBM01UZGFGdzB6TmpBNU1EVXhOekEzTVRkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBVU9LOGE5am1SK2p5RmE2allKZXBmYStQMis0RTVQY09ac2pFClM1Z0V2M0tqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVMnF6aWxVYTFtWGZhb3J5cQp1WUFjZmRrZjhiRXdCUVlESzJWd0EwRUEvUmg5WG96aTUxMkh1YkFwcUVHOXQwa0ZrdEVuOXVjMGZLUERVL0tnClkzK2xtKythMjM0bFBUTTZuazRHdUdGUnRYdERTUGVWdnlqZmwzR3hyYWFtQXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJRTNvRlN3M0JVMS9aa0ZPZ0dqNmtqWElxdTQ5Z0lML1JJME5qVTl6aEoyaAotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
  # Extra certificate subject alternative names for the machine's certificate.
  certSANs: []
  #   # Uncomment this to enable SANs.
  #   - 10.0.0.10
  #   - 172.16.0.10
  #   - 192.168.0.10

  # Features describe individual Talos features that can be switched on or off.
  features:
    diskQuotaSupport: true # Enable XFS project quota support for EPHEMERAL partition and user disks.

  # # Configures the logging system.
  # logging:
  #     # Logging destination.
  #     destinations:
  #         - endpoint: tcp://1.2.3.4:12345 # Where to send logs. Supported protocols are "tcp" and "udp".
  #           format: json_lines # Logs format.
  # logging:
  #     # Logging destination.
  #     destinations:
  #         - endpoint: udp://127.0.0.1:12345 # Where to send logs. Supported protocols are "tcp" and "udp".
  #           format: json_lines # Logs format.
  #           # Extra tags (key-value) pairs to attach to every log message sent.
  #           extraTags:
  #             machine: worker-1

  # # Configures the seccomp profiles for the machine.
  # seccompProfiles:
  #     - name: audit.json # The `name` field is used to provide the file name of the seccomp profile.
  #       # The `value` field is used to provide the seccomp profile.
  #       value:
  #         defaultAction: SCMP_ACT_LOG
# Provides cluster specific configuration options.
cluster:
  token: 7ipkjc.kqfczanejxa8isxc # The [bootstrap token](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) used to join the cluster.
  # Etcd specific configuration options.
  etcd:
    # The `ca` is the root certificate authority of the PKI.
    ca:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmRENDQVNPZ0F3SUJBZ0lRQ0JpbC9jdzVndjZRbjRLU092VnFSakFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURrd09ERTNNRGN4TjFvWERUTTJNRGt3TlRFM01EY3hOMW93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkRsMWxJVVRqaUxTClozNlVIMTRVempwN25qM0I5RjBvcTM5eGd5WlRtemlTS20rSWFKaXZhQ2w4SUFZcERNV0dNbVdqMUtBanJzVkwKd2VKbjFwdmh1aktqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVRE94VEtFVUluV01LCmdGQ1FBMDRqcDhicHFlWXdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdTajhRZHQ2S20rSkMzUy9BMEo0UlpZUXcKUmJKQVByMXExUlZONDdYckgyNENJSG5DUzIrU3kwRDBFaXVTRW9JU3ZuZDFmUUgvcFBCNnBzdzZ4VE41QWExUgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdWdEtGLzhUenZSSW9LZ0F1czFXUEcvclFzaDQyanBWNkNHdHgyRTZyQWpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFT1hXVWhST09JdEpuZnBRZlhoVE9PbnVlUGNIMFhTaXJmM0dESmxPYk9KSXFiNGhvbUs5bwpLWHdnQmlrTXhZWXlaYVBVb0NPdXhVdkI0bWZXbStHNk1nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

    # # The container image used to create the etcd service.
    # image: registry.k8s.io/etcd:3.7.1

    # # The `advertisedSubnets` field configures the networks to pick etcd advertised IP from.
    # advertisedSubnets:
    #     - 10.0.0.0/8

  # # External cloud provider configuration.
  # externalCloudProvider:
  #     enabled: true # Enable external cloud provider.
  #     # A list of urls that point to additional manifests for an external cloud provider.
  #     manifests:
  #         - https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/v1.20.0-alpha.0/manifests/rbac.yaml
  #         - https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/v1.20.0-alpha.0/manifests/aws-cloud-controller-manager-daemonset.yaml

  # # Settings for admin kubeconfig generation.
  # adminKubeconfig:
  #     certLifetime: 1h0m0s # Admin kubeconfig certificate lifetime (default is 1 year).
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default # Name of the discovery service configuration.
endpoint: https://discovery.talos.dev/ # Discovery service endpoint to use.
---
apiVersion: v1alpha1
kind: DiscoveryIdentityConfig
clusterID: hQWNaTkQa3eSVpMisgddqPKhYkvgs/CvjTPxPlu2/fs= # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
clusterSecret: Rrd161d6LhcrJUb0Ob6M6AIt/VIRdCAbiWxvTVf6rbU= # Shared secret of cluster (base64 encoded random 32 bytes).
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
# The installer describes the source of the installation.
installer:
  image: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.14.0 # Allows for supplying the image used to perform the installation.
# The provisioning describes how the installation disk should be provisioned.
provisioning:
  # Matches disks to initialize as physical volumes.
  diskSelector:
    match: disk.dev_path == "/dev/sda" # CEL expression matching a disk.
  wipe: false # Indicates if the installation disk should be wiped at installation time.
---
apiVersion: v1alpha1
kind: ResolverConfig
# Configuration for host DNS resolver.
hostDNS:
  enabled: true # Enable host DNS caching resolver.
  forwardKubeDNSToHost: true # Use the host DNS resolver as upstream for Kubernetes CoreDNS pods.
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL # Name of the volume.
# The mount describes additional mount options.
mount:
  secure: true # Enable secure mount options (nosuid, nodev).

# # The encryption describes how the volume is encrypted.
# encryption:
#     provider: luks2 # Encryption provider to use for the encryption.
#     # Defines the encryption keys generation and storage method.
#     keys:
#         - slot: 0 # Key slot number for LUKS2 encryption.
#           # Key which value is stored in the configuration file.
#           static:
#             passphrase: exampleKey # Defines the static passphrase value.
#
#           # # KMS managed encryption key.
#           # kms:
#           #     endpoint: https://192.168.88.21:4443 # KMS endpoint to Seal/Unseal the key.
#         - slot: 1 # Key slot number for LUKS2 encryption.
#           # KMS managed encryption key.
#           kms:
#             endpoint: https://example-kms-endpoint.com # KMS endpoint to Seal/Unseal the key.
#     cipher: aes-xts-plain64 # Cipher to use for the encryption. Depends on the encryption provider.
#     blockSize: 4096 # Defines the encryption sector size.
#     # Additional --perf parameters for the LUKS2 encryption.
#     options:
#         - no_read_workqueue
#         - no_write_workqueue
---
apiVersion: v1alpha1
kind: FilesystemTrimConfig
interval: 168h0m0s # The interval at which the filesystems are trimmed.
---
apiVersion: v1alpha1
kind: SecurityProfileConfig
workloadIsolation: true # Enable workload isolation (run the container plane inside the sandbox namespace).
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable # A method to automatically generate a hostname for the machine.

# # A static hostname to set for the machine.
# hostname: controlplane1
# hostname: controlplane1.example.org
---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: betty # The cluster name.
endpoint: https://k8s.internal:6443 # The Kubernetes API endpoint.
---
apiVersion: v1alpha1
kind: KubeNodeConfig
# The `nodeIP` field is used to configure `--node-ip` flag for the kubelet.
nodeIP: {}
# Configures the node labels for the machine.
labels:
  node-role.kubernetes.io/control-plane: ""
  node.kubernetes.io/exclude-from-external-load-balancers: ""
# Configures the node taints for the machine. Effect is optional.
taints:
  node-role.kubernetes.io/control-plane: NoSchedule
---
apiVersion: v1alpha1
kind: KubeletConfig
image: ghcr.io/siderolabs/kubelet:v1.37.0 # The container image used to run the kubelet component.
# Provide extra configuration for the kubelet.
config: {}
defaultRuntimeSeccompProfileEnabled: true # Enable container runtime default Seccomp profile.
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local # The domain used by Kubernetes DNS.
# The pod subnet (CIDR), this can be a single value or two values for dual-stack clusters.
podSubnets:
  - 10.244.0.0/16
# The service subnet (CIDR), this can be a single value or two values for dual-stack clusters.
serviceSubnets:
  - 10.96.0.0/12
---
apiVersion: v1alpha1
kind: KubeAPIServerCAConfig
# The currently active issuing certificate authority for the Kubernetes API server.
issuingCA:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIBijCCATCgAwIBAgIRAPCVJt/nCNplnGp4whSTO7owCgYIKoZIzj0EAwIwFTET
    MBEGA1UEChMKa3ViZXJuZXRlczAeFw0yNjA5MDgxNzA3MTdaFw0zNjA5MDUxNzA3
    MTdaMBUxEzARBgNVBAoTCmt1YmVybmV0ZXMwWTATBgcqhkjOPQIBBggqhkjOPQMB
    BwNCAATlqxYIxJz9BlRJiFu2VHnAMJeWeTrnxVT3voxzyKhnQhMrZo6XkkLf+NnK
    M6ZyIM+abL5hHoIszVe9AwoBlmD4o2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0l
    BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFOEH4MXMNwz4esc00PgMUYoPkbQqMAoGCCqGSM49BAMCA0gAMEUCIFqVLEv3
    kRIkjiR6MN+sOtFqs5SYfm70Brz9L2LLn9N/AiEA6zLZuGPXxcZAA/6QmGvVnglC
    oXMCClC/A/mfz/pjuCk=
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIP4Dy5P4VnQR+mZgWulgVIxMdL7oknulCkuaQ/y+IAm4oAoGCCqGSM49
    AwEHoUQDQgAE5asWCMSc/QZUSYhbtlR5wDCXlnk658VU976Mc8ioZ0ITK2aOl5JC
    3/jZyjOmciDPmmy+YR6CLM1XvQMKAZZg+A==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445 # KubePrism port.
---
apiVersion: v1alpha1
kind: KubeAggregatorCAConfig
# The currently active issuing certificate authority for the Kubernetes API aggregator flow.
issuingCA:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIBYTCCAQagAwIBAgIRAMfKvApsiAMQk7YTEfADhDAwCgYIKoZIzj0EAwIwADAe
    Fw0yNjA5MDgxNzA3MTdaFw0zNjA5MDUxNzA3MTdaMAAwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAARmdpGGDR65L4HecRn2FJWLo7ombcy7fm/Z5edAMKTjZgop4vpv
    TUdPOxd8IVAdEdAKSy77j3+9yTvlwk8NIF9+o2EwXzAOBgNVHQ8BAf8EBAMCAoQw
    HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8w
    HQYDVR0OBBYEFBcLboOeBjG0XhQwdE4O6lUjRmUSMAoGCCqGSM49BAMCA0kAMEYC
    IQD6af1hh/wjDVFBSCtS5UKt3gKZFL6zYeGroKPeXPFRkAIhAL/3uNoz2EuyhJxT
    sXEmKhh2B6mEdq/pEaCfF4mDjbNq
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIKyZKLpU416xf9hZ1cyRSllYi3rLwBJzAu39eb1x0NUIoAoGCCqGSM49
    AwEHoUQDQgAEZnaRhg0euS+B3nEZ9hSVi6O6Jm3Mu35v2eXnQDCk42YKKeL6b01H
    TzsXfCFQHRHQCksu+49/vck75cJPDSBffg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1alpha1
kind: KubeAdmissionControlConfig
name: PodSecurity # Admission control plugin name, should be a valid Kubernetes admission control plugin name.
# Kubernetes API server [admission control plugins](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/).
configuration:
  apiVersion: pod-security.admission.config.k8s.io/v1alpha1
  defaults:
    audit: restricted
    audit-version: latest
    enforce: baseline
    enforce-version: latest
    warn: restricted
    warn-version: latest
  exemptions:
    namespaces:
      - kube-system
    runtimeClasses: []
    usernames: []
  kind: PodSecurityConfiguration
---
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
# Kubernetes API server [audit policy](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) configuration.
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
---
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
# Kubernetes API server [authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) configuration.
configuration:
  anonymous:
    conditions:
      - path: /livez
      - path: /readyz
      - path: /healthz
    enabled: true
  jwt: []
---
apiVersion: v1alpha1
kind: KubeAuthorizerConfig
name: node # Name of the authorizer, should be be DNS1123 labels like myauthorizername or subdomains like myauthorizer.example.domain.
type: Node # Type is the name of the authorizer.
---
apiVersion: v1alpha1
kind: KubeAuthorizerConfig
name: rbac # Name of the authorizer, should be be DNS1123 labels like myauthorizername or subdomains like myauthorizer.example.domain.
type: RBAC # Type is the name of the authorizer.
---
apiVersion: v1alpha1
kind: KubeEtcdEncryptionConfig
# Kubernetes API server [encryption of secret data at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).
config:
  resources:
    - providers:
        - secretbox:
            keys:
              - name: key2
                secret: VrwOLttrSulD4NNydYh3rm0WVNCjJkmNYwmYIu/tfnk=
      resources:
        - secrets
---
apiVersion: v1alpha1
kind: KubeServiceAccountConfig
# The service account issuer configuration.
issuer:
  privateKey: | # The key which is used to sign the service account tokens.
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEA20eFmz7opLXP7jZzs2g86tPjoBC0/tB9HDY0niTOBYmtqIr1
    7WAXAOJMyWUT265iFkybMY6lfAy3s0dwQI2YYcrlgh/dIFSTvwa+jXLA/WdMOBUQ
    UGII1XDubjRVnedX1bRaCulYTm+rFUrZZmxbSXNDod/F3RYVnTtzKSfWgTUwDcVj
    8zy/RJr9lIqkoF0Ym+6JkGm0rVIxCjvvWpfd27tbtiwd7VCsyGZ7qwFmX/UeEJAs
    J1SrpykJx90Z3VEzUUSAWtYvCbRoaaVhewjcRzmR8Sv8h2cngeOXmDkImKf9GRfU
    pPqBbgtw/3tGGnXl077QPLq7JySoCs4Y10gDrJwN6942OPxapB/P5j/M9FK8cKqf
    zi3kLukm/IHHmxH35tzTuShrTJ9f32No5AgtRCQ30oxVXMw4VtsTx/9hQK+oa2/2
    8b7EWdJeCodpKuP1CMwnSJZzPej1f4Vmt0RZgRYKDdy1v3TD/wAcHdcSc/owJUZj
    eIDUuQbDfcOWsP7LJne3a4TqfVz+SCw4EggG7pCWK4uSGJNEQe4cnLib3j1Lihg8
    BUKCvTEzaAIcBelWYfF9fvJJ0Pyn0QmZOz9wMnKg5AHV0OpuW3gssMJKeZS1XfMR
    WzPxM2nLbLJQfTe+/AuZMiysyv+2Wm+uM5XrXgNGz9k5KWGBWayezdMcxxUCAwEA
    AQKCAgAjHlFHi8u2lWe3vwDIuukGsujBuetC5CElY4kJyts0B9jIJXk9iyYj/hpO
    JuIHTOZoq9wvE6ltNJw3GjngHM1K3DPlozTG+MSw02OxQ6+k5eZPFRCHzyubA3ss
    KzWLFIH8t+Wz2atK5JeB0Xr/7FqyaMNsKWqG/gJ4LA1FihvQlbQcgICBdDktw6TZ
    JVs4U7CdSJa/ii5lk8RG31J2L9xYVKlbg7VHTKRfdApaWN8MfzVRccWghu721pu6
    Zq69w0N0wIPOCH+ADmSqhtIV4lVlEtNMzL6k8OBi7RBaUMgPqtfeLPLheT1BYpO2
    VwfjNP6Z6vVuxHk0y6oeEOPplp7/uhowdM0yvpBuaHydXECfpFJJ5CwYJuGbeOPu
    vqMpBkydqGFODTVnyBe/jdLjPZdrFdDaSjAnFCJYrdL2shB8oCa7r8J5v0JJdkFY
    E3cO6W14sGKquEXjSRBet1r4QvJLi1ohOAQC/GzmWOcaMUyVEgvMSBNgF0S+3nq2
    Q94Hrlep+pg4WussXO3qFqN45Ezhzm90b9XlWeVAqEbSK1kFwKz4Qk5/Rt/XM5Sq
    8lM3SwAY7qXVKni5wP7ZB/lXeI7scfmmuk+j9r8LwoeRo8kxWkV0ze9FeWMcrcW5
    9YtADtE+d1jzmW3uzwHbk2sEXU0DA5RZ1crBql/1WhhBqiNsAQKCAQEA7bZmaP74
    T/qGaAYdZCjjmL+CFstmqEmrM9JYOl3+5RB0zoEvdWKwG4wSaVHxNcK+SJQvGdAe
    4cLgm5nFicrD6j7UNLj9+/5dl9gJACSb5hxeJb7lG6dKDgUbLrxQI8Rgd97JPoAZ
    oG2HQxldcf3sUmUUrtLIFwsH/A9ahmkkOM4XDttCKYFfbaFo6QLZL+MnJbmZPB9c
    2eIpvunwrUgBWxad5mJsnOePxI3yqMS9R2JFhJzh0kGfe85DoKEQvivN83FtD6eF
    ep5K1e51BEBOld7Jk96ZrVw9yuF3yoyihJPkDgAoMdlgTK/xYE4GnvNSpaSINuVm
    3N9c8622YiQIJwKCAQEA7CYX0u57tBpWFfVZbBSOQ7JwXwAzi//rpbxCp8GeSUEa
    6OJhil0sL4vPLraIRg7+gsM+4qfxUtB3ah6VEYKd7SKq+bnRYIdVYthjXMCZIEap
    6/wFKgBag9NS+rjZ6OkREMMoE++GmWnpjErfBOo6a6yqpNeDqnNMR7z/XwY+bD+W
    xOdoHBrj+zWtM0Rz+MeIT+dtpQzAzWrQDKyQSLaRVHtWv7vmLKbugv2wftlj/kLY
    KckbKp65dhp6gw7QT/DCIiieQ5YkQbDIyltmZGjfNCKzHlGAiLbDQfooiGsh3nQi
    tTjFoQhJ/lNrqcBgRielf2fOaT1Vg9AK6o+iT0lgYwKCAQA+XmwSQkuOWHHpWylc
    /SlyC1Ure+SMZP/JUfgaIE1fdmjfQZ/dEa6ZG7A89+XssBLS4iZVhHiFzWa3DKp6
    k7vBewicaKki88NEssbxxaktv+Wny6U7EzJn6UkPgxMXv098Q/TTNDMFF5e0sDQH
    U5Msrx61G9Kp0RggNzsOJwn86X29RSPf1fTew8nN0RSA7v13dXHSB3yKIj/HuoOO
    Q2UvrAhzyQEsTck3zfKL+0qaLxuERtEtJFCe4Ch4Paox6zZXGDyALfjkiiGibbVA
    D0tPISwMYww5IwmHcI7IkwuU82STk9D3+0u78zHGjdJI5BicI0Yl+Rx6+RPfT4WZ
    zFBjAoIBAQDp/YzZuujkOrxWIbgreerFdYgW+jIZZMpwfKxnYVigKVyqqbYQzeW8
    bwIpvUAmezEBDMnA+LwMXPgWNJtssEof8JwNumuXBEI9IUDDZSvVaW9xn1TWm2cU
    /E5alNOHD3mTbGzH5C0w0ltSYdW+HwEoM/0aPVn/iSNqagF4fM1ZoWCZVto4DwUb
    o8Is7IUlW0DcO+rPAmYApPfltw94nT4/wb7hWSPn1ri7HvjFmE6WYFGkhdrfTkti
    lTYTqpgKvfr+sdSwD5N5a9xpdkts7uVL2Z42Snfb/4xWUbPcCJuUuuqxOsHIoFgB
    I1Oo7i/3E83PAmLqsJWNeJV4ej5P5dsVAoIBAGiMMOT5jwfpkVk06jGy09GN5QJg
    V9lJWKw2hba25SDddqmCqH7SVzkOAhacLqruPKb0Aic0BBh2TCCfoB1sRM75vuKl
    JbZdDCoah8tCmpcdDxpiokFzsKjfX9SUKUUUQENIfIkW78RcK37PqMZRuFa5ili3
    9uVU4ncKIlve7l9JfxI+o/ryYyi69zuoQjU27mamnBmDdfJMS4gHmym/zvq8zsrj
    JwH1z6LVaTrpv0mfrz2adMvi4ZZIOF+/5MRaYU3puxk+zp7ciiyuatjBPGLZGNFy
    yYEYmxkunA9c4g9F4kJ79MSBJuxLXWJNow1y89QNPbvYO7z8Usj6D81d4gs=
    -----END RSA PRIVATE KEY-----
  issuerURL: https://k8s.internal:6443 # The issuer URL which is used to sign the service account tokens.
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
image: registry.k8s.io/kube-apiserver:v1.37.0 # The container image used to run the kube-apiserver component.
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
image: registry.k8s.io/kube-controller-manager:v1.37.0 # The container image used to run the kube-controller-manager component.
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
image: registry.k8s.io/kube-scheduler:v1.37.0 # The container image used to run the kube-scheduler component.
# Provide configuration for the kube-scheduler static pod.
config: {}
---
apiVersion: v1alpha1
kind: KubeProxyConfig
image: registry.k8s.io/kube-proxy:v1.37.0 # The container image used in the kube-proxy manifest.
# Provide configuration for the kube-proxy.
config: {}
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
backendType: vxlan # Type of the Flannel backend to use.
backendPort: 4789 # UDP port used by Flannel for encapsulating traffic (if the backend type requires encapsulation).

# # Extra arguments for 'flanneld'.
# extraArgs:
#     - --iface-can-reach=192.168.1.1
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: true # By default, CoreDNS deployment is enabled.
