version: v1alpha1 # Indicates the schema used to decode the contents.
debug: false # Enable verbose logging to the console.
persist: true
# Provides machine specific configuration options.
machine:
  type: worker # Defines the role of the machine within the cluster.
  token: ho6bzi.4laeze1du7vvrixf # The `token` is used by a machine to join the PKI of the cluster.
  # The root certificate authority of the PKI.
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJGVHBDZXpYbktqcXVCSUM0NloyQ25NQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTVNRGd4TnpBM01UZGFGdzB6TmpBNU1EVXhOekEzTVRkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBVU9LOGE5am1SK2p5RmE2allKZXBmYStQMis0RTVQY09ac2pFClM1Z0V2M0tqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVMnF6aWxVYTFtWGZhb3J5cQp1WUFjZmRrZjhiRXdCUVlESzJWd0EwRUEvUmg5WG96aTUxMkh1YkFwcUVHOXQwa0ZrdEVuOXVjMGZLUERVL0tnClkzK2xtKythMjM0bFBUTTZuazRHdUdGUnRYdERTUGVWdnlqZmwzR3hyYWFtQXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ""
  # Extra certificate subject alternative names for the machine's certificate.
  certSANs: []
  #   # Uncomment this to enable SANs.
  #   - 10.0.0.10
  #   - 172.16.0.10
  #   - 192.168.0.10

  # Features describe individual Talos features that can be switched on or off.
  features:
    diskQuotaSupport: true # Enable XFS project quota support for EPHEMERAL partition and user disks.

  # # Configures the logging system.
  # logging:
  #     # Logging destination.
  #     destinations:
  #         - endpoint: tcp://1.2.3.4:12345 # Where to send logs. Supported protocols are "tcp" and "udp".
  #           format: json_lines # Logs format.
  # logging:
  #     # Logging destination.
  #     destinations:
  #         - endpoint: udp://127.0.0.1:12345 # Where to send logs. Supported protocols are "tcp" and "udp".
  #           format: json_lines # Logs format.
  #           # Extra tags (key-value) pairs to attach to every log message sent.
  #           extraTags:
  #             machine: worker-1

  # # Configures the seccomp profiles for the machine.
  # seccompProfiles:
  #     - name: audit.json # The `name` field is used to provide the file name of the seccomp profile.
  #       # The `value` field is used to provide the seccomp profile.
  #       value:
  #         defaultAction: SCMP_ACT_LOG
# Provides cluster specific configuration options.
cluster:
  token: 7ipkjc.kqfczanejxa8isxc # The [bootstrap token](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) used to join the cluster.

  # # Etcd specific configuration options.
  # etcd:
  #     image: registry.k8s.io/etcd:3.7.1 # The container image used to create the etcd service.
  #     # The `ca` is the root certificate authority of the PKI.
  #     ca:
  #         crt: LS0tIEVYQU1QTEUgQ0VSVElGSUNBVEUgLS0t
  #         key: LS0tIEVYQU1QTEUgS0VZIC0tLQ==
  #     # Extra arguments to supply to etcd.
  #     extraArgs:
  #         election-timeout: "5000"
  #     # The `advertisedSubnets` field configures the networks to pick etcd advertised IP from.
  #     advertisedSubnets:
  #         - 10.0.0.0/8

  # # External cloud provider configuration.
  # externalCloudProvider:
  #     enabled: true # Enable external cloud provider.
  #     # A list of urls that point to additional manifests for an external cloud provider.
  #     manifests:
  #         - https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/v1.20.0-alpha.0/manifests/rbac.yaml
  #         - https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/v1.20.0-alpha.0/manifests/aws-cloud-controller-manager-daemonset.yaml

  # # Settings for admin kubeconfig generation.
  # adminKubeconfig:
  #     certLifetime: 1h0m0s # Admin kubeconfig certificate lifetime (default is 1 year).
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default # Name of the discovery service configuration.
endpoint: https://discovery.talos.dev/ # Discovery service endpoint to use.
---
apiVersion: v1alpha1
kind: DiscoveryIdentityConfig
clusterID: hQWNaTkQa3eSVpMisgddqPKhYkvgs/CvjTPxPlu2/fs= # Globally unique identifier for this cluster (base64 encoded random 32 bytes).
clusterSecret: Rrd161d6LhcrJUb0Ob6M6AIt/VIRdCAbiWxvTVf6rbU= # Shared secret of cluster (base64 encoded random 32 bytes).
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
# The installer describes the source of the installation.
installer:
  image: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.14.0 # Allows for supplying the image used to perform the installation.
# The provisioning describes how the installation disk should be provisioned.
provisioning:
  # Matches disks to initialize as physical volumes.
  diskSelector:
    match: disk.dev_path == "/dev/sda" # CEL expression matching a disk.
  wipe: false # Indicates if the installation disk should be wiped at installation time.
---
apiVersion: v1alpha1
kind: ResolverConfig
# Configuration for host DNS resolver.
hostDNS:
  enabled: true # Enable host DNS caching resolver.
  forwardKubeDNSToHost: true # Use the host DNS resolver as upstream for Kubernetes CoreDNS pods.
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL # Name of the volume.
# The mount describes additional mount options.
mount:
  secure: true # Enable secure mount options (nosuid, nodev).

# # The encryption describes how the volume is encrypted.
# encryption:
#     provider: luks2 # Encryption provider to use for the encryption.
#     # Defines the encryption keys generation and storage method.
#     keys:
#         - slot: 0 # Key slot number for LUKS2 encryption.
#           # Key which value is stored in the configuration file.
#           static:
#             passphrase: exampleKey # Defines the static passphrase value.
#
#           # # KMS managed encryption key.
#           # kms:
#           #     endpoint: https://192.168.88.21:4443 # KMS endpoint to Seal/Unseal the key.
#         - slot: 1 # Key slot number for LUKS2 encryption.
#           # KMS managed encryption key.
#           kms:
#             endpoint: https://example-kms-endpoint.com # KMS endpoint to Seal/Unseal the key.
#     cipher: aes-xts-plain64 # Cipher to use for the encryption. Depends on the encryption provider.
#     blockSize: 4096 # Defines the encryption sector size.
#     # Additional --perf parameters for the LUKS2 encryption.
#     options:
#         - no_read_workqueue
#         - no_write_workqueue
---
apiVersion: v1alpha1
kind: FilesystemTrimConfig
interval: 168h0m0s # The interval at which the filesystems are trimmed.
---
apiVersion: v1alpha1
kind: SecurityProfileConfig
workloadIsolation: true # Enable workload isolation (run the container plane inside the sandbox namespace).
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable # A method to automatically generate a hostname for the machine.

# # A static hostname to set for the machine.
# hostname: controlplane1
# hostname: controlplane1.example.org
---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: betty # The cluster name.
endpoint: https://k8s.internal:6443 # The Kubernetes API endpoint.
---
apiVersion: v1alpha1
kind: KubeNodeConfig
# The `nodeIP` field is used to configure `--node-ip` flag for the kubelet.
nodeIP: {}
---
apiVersion: v1alpha1
kind: KubeletConfig
image: ghcr.io/siderolabs/kubelet:v1.37.0 # The container image used to run the kubelet component.
# Provide extra configuration for the kubelet.
config: {}
defaultRuntimeSeccompProfileEnabled: true # Enable container runtime default Seccomp profile.
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local # The domain used by Kubernetes DNS.
# The pod subnet (CIDR), this can be a single value or two values for dual-stack clusters.
podSubnets:
  - 10.244.0.0/16
# The service subnet (CIDR), this can be a single value or two values for dual-stack clusters.
serviceSubnets:
  - 10.96.0.0/12
---
apiVersion: v1alpha1
kind: KubeAPIServerCAConfig
# The list of accepted CA certificates for the Kubernetes API server.
acceptedCAs:
  - |
    -----BEGIN CERTIFICATE-----
    MIIBijCCATCgAwIBAgIRAPCVJt/nCNplnGp4whSTO7owCgYIKoZIzj0EAwIwFTET
    MBEGA1UEChMKa3ViZXJuZXRlczAeFw0yNjA5MDgxNzA3MTdaFw0zNjA5MDUxNzA3
    MTdaMBUxEzARBgNVBAoTCmt1YmVybmV0ZXMwWTATBgcqhkjOPQIBBggqhkjOPQMB
    BwNCAATlqxYIxJz9BlRJiFu2VHnAMJeWeTrnxVT3voxzyKhnQhMrZo6XkkLf+NnK
    M6ZyIM+abL5hHoIszVe9AwoBlmD4o2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0l
    BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFOEH4MXMNwz4esc00PgMUYoPkbQqMAoGCCqGSM49BAMCA0gAMEUCIFqVLEv3
    kRIkjiR6MN+sOtFqs5SYfm70Brz9L2LLn9N/AiEA6zLZuGPXxcZAA/6QmGvVnglC
    oXMCClC/A/mfz/pjuCk=
    -----END CERTIFICATE-----
---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445 # KubePrism port.
