#!/usr/bin/env bash
rm -rf charts
echo "# This manifest was generated by automation. DO NOT EDIT." > ./coredns.yaml
echo "---" >> ./coredns.yaml
kustomize build \
  --enable-helm \
  --load-restrictor=LoadRestrictionsNone \
  . \
  >> ./coredns.yaml
rm -rf charts
prettier --config ../../../../../.ci/prettier/.prettierrc.yaml --write ./coredns.yaml
