#!/usr/bin/env bash
rm -rf charts
rm -rf ./values.yaml
echo "# This manifest was generated by automation. DO NOT EDIT." >./values.yaml
echo "---" >> ./values.yaml
envsubst </home/stephen/Documents/Development/home_cluster/kubernetes/apps/kube-system/cilium/app/values.yaml >values.yaml
kustomize build --enable-helm . | kubectl apply -f -
rm -rf charts
