---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          *app :
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728

            env:
              TZ: America/Boise
              RECYCLARR_DATA_DIR: /tmp

            envFrom:
              - secretRef:
                  name: recyclarr

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"

            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      *app :
        controller: *app
        enabled: false

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"

      recyclarr-configs:
        type: configMap
        name: recyclarr-configs
        globalMounts:
          - path: /config/configs/sonarr-config.yaml
            subPath: sonarr-config.yaml

          - path: /config/configs/sonarr-anime-config.yaml
            subPath: sonarr-anime-config.yaml

          - path: /config/configs/sonarr-uhd-config.yaml
            subPath: sonarr-uhd-config.yaml

          - path: /config/configs/radarr-config.yaml
            subPath: radarr-config.yaml

          - path: /config/configs/radarr-anime-config.yaml
            subPath: radarr-anime-config.yaml

          - path: /config/configs/radarr-uhd-config.yaml
            subPath: radarr-uhd-config.yaml

      tmp:
        type: emptyDir
