# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr
  namespace: media
type: Opaque
stringData:
  RADARR_APIKEY: ENC[AES256_GCM,data:BDurselnLa6La6aUJ+VGNDrAc37dzgRDiIXK0Or+Aag=,iv:iy9SF3Nv6oerKbCQzrA86m/Qu5d8NADjq2xH/EYBvug=,tag:u4+kc3BVZJh16JbiKMzKFQ==,type:str]
  RADARR_ANIME_APIKEY: ENC[AES256_GCM,data:9zBU6N1wLclYU7qnmCYJ2bj/EyLVjB/XF8Hdr+NND9E=,iv:+2nQMlSowVb2VK7w5OpbltRHRp1t6kwqSnQKucbPdDI=,tag:4Mk7LYw6h2q6YTui7V4CQA==,type:str]
  RADARR_UHD_APIKEY: ENC[AES256_GCM,data:zPY/rkniUaJQNS12yPQRrfmDi0CEGWTJ7N87BFGYpmE=,iv:F7L/K0go2WZOekrhLLaszuPshNqr9kCK4yjT2BJbDN0=,tag:F9mIuvXbnVVR6dg1eJEiaw==,type:str]
  SONARR_APIKEY: ENC[AES256_GCM,data:tTFtyYjzlqM6n4YrYBmJNDWVuIvgG+F1yqk7tZxkkN0=,iv:5bKx9JUDfdgwhaTCXvUSnygQedsPfW9tvfKoi2bzGho=,tag:7/HI52NjD7+wWNN9VkleRQ==,type:str]
  SONARR_ANIME_APIKEY: ENC[AES256_GCM,data:C4Af+maCWwf3cr2H2Y5d6RdY6xMitY1qGU+xssj6+no=,iv:59nv9+noLugw8Ku+Wv4o7REx9Dedh1pPhPw/qltw2E0=,tag:Dz9xwtw/bfF/kNfY9VR3ag==,type:str]
  SONARR_UHD_APIKEY: ENC[AES256_GCM,data:lIVb7nMw3UnZLAdwEiB/JHHBaDT1il6+TcXyt20M9JQ=,iv:CcnAR8luxOvbShGUtQZ5taWY/zc1vSyNLnNTITCE8YI=,tag:NbQnpHPFF3oHgsMNYn0TTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGQzQmQxcUNk
        Q1h2aHgydzJ2ZFpTYXRiWWpTVEVXSWM2Qm4rTXZIVWZsMTFoRXEraXkxaGUzYURn
        YUZZcEpPNXQ3VlNFR1FBWGlxd3BwTWc0ckFjaXZVRjd1YVF0elpyVS8zZHNWRnk4
        WXA2ZUtHS0h0bVc1NmRWRHZFT3IvTzlDSy9DWG5nd2VpYy9NRUNQY0VYd0NCcjZV
        UUdVUXN5aHNpTzh0UGdWRDdYMHgwNHlrb3l4dWRqZ2VKTjRMWGp1aUhTcTd5emVZ
        SGlEVEtYbEM5ZmRPcjFhVDNRek5INVRrbUwzSzdWRkRaYUE0S1ZOeHpjT2RZenlx
        Q3hFT0RkLzU4aENaQTVCdFFWZnl0SkdGbFFRYXkxNDZXN3JTK2RMbDl3L0ZTWEh3
        cHZaaFhmMXZGV2JQT2ROL2xrV1ozRTZoaEUxQXlVb2RuWEpSNkU4cEh6aEpPWlJD
        bnd5azFqZzFpVmRTM1ViZ21CVURGNlRCRmVrR2pHMHE0MjNSOFVRaU9SbnVPR2lY
        cGhNbkFyK3hmaGUyenBRRUUyWG4wVnE3TGthUnFsZGI5Y3Y5SlQvM1c5ZFJJb0Rj
        T1B1QnJzYjV6THhkUFVQemZBUTBRQ2lnQlZpVVQrSXpzOWVtUEludms1ZWI0WnFO
        eWFlclVWZU5DZ2QvWnkxZUpvVFhkSHFMOVEvelhaSXk2NDIySG9hRXRiTTR2WUQv
        MHlLS1hZdmxvVHdwMm5wb3pFcnB3UUpFRGJJWm8vM1BhamorODc1VGIzWWg1bWJG
        cWw5anJJdlAxWG81bEFZd1k5S3ZpclVhVUlWams2Y2JzT3FlV0U3cFArL050dmpr
        WGlsM1dtRGdOaHZyYWwwRkFCSnBYTFAreC9KV0dZenRGSXR4S1lBNkNtODZqazJ5
        eG03OHNPODNTRlBpRjBXWTZncUx0Q1h5QlBGZG05NTBSTmFUL01qVU9oQWlPYSt5
        eEhNcGp5TExCMW9pRGhDelh2T3FlSTYxQzJ1NzBQREJvT3pOeGhmSjZESC9VMFV3
        eEZKRENESVlack9lc1VoVjFodlk1VVJhbGRkRkpNRkJvNElTekdqR2pFcERZM1Z3
        ZE5kOEp4VUxqV1YxYW1pM0dQV0p2ZmZ5TzdSMnhQdFJRNHB4WHdObndLLzdTMTRs
        TktMYUJkRmpZYUFnREpoUG1SWThCVEplM1VEaGorSTN2NnZTcjJnSDkzQ3dLQytW
        bmJFWVVLNXhWRDlFMEdRUVJxNExNWFdpazZ4dGt1aTR1djV2WkRDWEtiamhkMEdH
        OU93dzZhTHpGaDNLNHpKbS9FQWM0WTBQL0FXUzdQdkgzblJFSDBpL05zTlJWc09z
        WXlMdFB3eW1CTVkvNHVnSW12bjhEbXg3RDArNDhxM0w4WHZHSnduUFdDdElRTWZF
        allKMVY1T3BOSHlDOVVKa2FzYXRNM0d1SFdBOHJCZHNyNytIQ0VoNFZEZmM3N0tR
        dVhnMUFaaUhqV0JFVC9YdGdrdFp4N2hpVFhScnBLV3JGc1ExQW9LUXN4eXVDSC9M
        MmNBU0RyS3BxQngwMThxek9ZbFVEcitMZWVYNUxlOWh1aGRUbytOV1UzQVp4Zngx
        YklpazFpQUVBci9SajZERXJIbndka3RncjBhRmJWQWJtTW5hVUhCVXVkaDVLVVRJ
        eGFMQThkckZVVzF1SEV5bXZVb1laZ3ZHQk1nRlNlTm5ibzE2OE5kbC9TZGVQUkE4
        M1o3cWpqOG5CS3JqM05Wb01WdStBSkhZcUJ1YitxZHpucWIxaWMyTi93TFM1R1o2
        bm0rZ2ZuWlVwT2tFNWNDV21FaGRWRlMzVGFiMzB5NFlvbHhRWGxRRlpIOUx4TTVo
        TGN5NkltZXB6WEpkRmRRS0d5RGZCN1hTUit3TXE4TFYxMm5ZL2liYVRGaCtEWXdM
        QzhuSGg1ZzNLUWNyK2hFckl6R2dZOTNERno2b3U0VmxVMVVtUXIyd3dPaUNZQQov
        UW9vQkpTbjlhTW12YVE4bFkyK1V3MEJJandKR0IwbmJHM2FDUFltdWljCi0tLSAw
        ZlVRb3VxSCtMMnBWZVJQK2JqTVgxenEyWkFOL3ZNM2JvTHI2MDcxeHVzCsbsVFF7
        Q2aHAkeDNLidjjN1ePKPUXlyB1RZCYlpqxACtojHGZ+8fvFQrt+N+NiL5ZSc89+i
        m+y/8dDax0d00Ek=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1q25jc4rp25dq0tpnc4vkwxr6ke6mqevjvcue3fcxv9292sxdvzzfz3n6k73rssk8zjap9c3nqtszxgaz27vm4qzlfzaampglkqf4e7h8rhqy8y09u357j5e35rsz8zxuwafuxr9rxe2qhkszal697e5tskjt0dphcctdm5c793yqpdh42uchnslllzetck9f9fdpkcgpcjfa52j7zuv40wsutgf2ad34vqy7pwzeg3nq0g248l45vsdxzprakzentq37d7p8nhft7j9tj99ccj04tqk38xclrht3pzekrhjpz66fz2q8ck36mjqsf5efz25ycgpz33ekkcvwvhasd5ruyyt8cez4prz8hk4pukd6xvmuzfezf08zngqgunzwepg5a5lj9nfhz5se565vexjz4k7tjzgzdlzyhj2a3vm8p42j3xvm4yxuk3qeh0x7756l9c7qxn5hs0wurl5ppp3z5svq68q5gtcp2vf3tux79z8225xx49enwtdj04vvcg0lgyddm3qm4ymudt7ggk9vc0n24zfewj4dceph7m9sa05vphajzrugj5y3mjy9umpshdue39n62fkmewy0zf9pd4atcfg3qd5e0dtleqq4s93d2mn589arwj3hqy5jp277pzxzvspz5kj5wcarkp6nzu2spdvjxwgvqvg2w3sw4de462u84tpgnfu6qvmrdzmafg26ewk9mj2ld02qmw2f97qex427s7tdfdk02cm9e7x5yqr9ktrn32pflc2vlunh4jayqn3atxnns3uu9u32k94eehvyjm2kxahr5yuy4yc054c2cnw4q9ensrqsqjy084r3rfzy7pjpesn3h9st397henyd5u46c434d74x0yq2f95ayjut2gte9mhffsgq3tmd2zzppatj9x6t7xcj43updyh2pg82keex90ykk9jzqlup83rd3z2fyenxxaqv9ud8ffamdfevdq843nzadn48ay0cswyt27cjepl4zprt3vfkmrdyy7y4zedrefe37fum39s8th6nk9h7ghvz8guvc7tp5c2eskly0w3ljksevvsaga4r9wgrqhrm3y8r5aq2h3cxka5knnpr8xvt5juudvqeuggd25sppz2v576rcfkpfy432ryvqj9uk6mvxzjywsxv4tahx62qjxqcxwuy9sscx48l9wtf67kax2s95latd22h0cvvgcyqkptrl7ekvcnfgnps3kst8re94sfpn7pzc74m5e3x8y480ty9j4tu5cax4xuujxt84l4s4f2h6pxn2zrh5juykjpcx3ftzfghx9w0mewxk0j4z3j8946qvqjn9wlw5jza4sa6kpcyyhlgyppnl39tyw6jgl6sj9epww4d9zyl5pwu59p0cmdhvqg54j2rvycvwcaq4qa5gqeynp83yf3awjkl3pqcfvr4gsy4d7x3sae72936za065kmwg864yx3c3pmlvhprqjl423tcshcvxtrnrza9z2znfvy0yk2rujp68wjuxxzkcs235lqp9yaqhuguanrt8xgsftdpvfg5jxvpet3qjpxz9gv3j548epx2yuqghhxqvm7hc2e782wfywhwnu5vp4emhglgnekz03p7awz0rqmmelpys2d6z7f2986zhwhacjt9pdx8ly5k4gk0r3qunsa52npm7ypq52h5s69ph3vdsupjacq6v2kx0f9x8zm3e0w0hsmwsu5z27q63985zdu3rgjcxur87wad3qyxntl45qa4dydtcayk7zna6tn307qmtwz4jhh7qz2sew5zgkdvlm4rsj0kye2uf0pmmy6tw75c90qtqytgk7sgnw845htwej8rrfa3qw7kta8j3pmhlfjka5nhq7g5sxw5u4cd98nr3rgmp6vgpcyrpkt29ufjuagkkzf5vv24svtvfy4y3luyud7uhktjvcthtrnz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T21:10:41Z"
  mac: ENC[AES256_GCM,data:S7y6PTBHUBzVRle5JRT0ovag83lMLX3rjIWVVsRgVoaxoxfM49NBJiws0nj4azTwCtUw/7x0Hphod4HJWq0zVmZeQV/Ka4Be0W0BVA2ZfFR3yHKiydqXEb+KXgyNBQwped2hT3NBDzRhP7cKMKU9jvt1jJ+xnIhrguHQmXBB9P8=,iv:MmlL5KNcFReQwSLBfwt6Tp9TS7Gfrb4wqylkCkF3MiU=,tag:jPM502qGWkfUoonIjvSAow==,type:str]
  version: 3.7.3
