apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:3pUxZ/GnVswnJNg=,iv:Z0X79ji/TETFZZdtbvhPFhaUIS4niT3iHkKKDdV6N4M=,tag:cxirHnevJw34BpcSKgIb4Q==,type:str]
  admin-password: ENC[AES256_GCM,data:zdMM7nzsVtTkcEM=,iv:ilV2NHWduGY2RGA8O905lu2I+FRtdsVvvjkz9K4I4QM=,tag:g3VJ5Iy6wLTcnrcIe69+ig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC9CcUM4a0Na
        WUNnK3duK0RkbmdwMkFvL0FKb3llaG5jSEJwbVNGdzBZRUxxL2pZZk5vUkhpc0RS
        VzZQdTZKaUVvT09WSGZlRXFOZDBRcGc5STRneG1oOVN1V09raVAweVFRU25MbHJP
        Z2dJMzE2M0dhSTZHdlZ4bXBrSDB0b2dXVUgzZnpvZjJuMVR0YmlQM05nQnNGUnFR
        OURHNTVHSEFQL2tvNkhFOHgzZzRObTI4RFhaUFBpNHV3OU5oM05ETDNSTnhhTGY4
        SDBxejNVbDhJQTNPV0FyaW8wRkdiN2YxaVhRcTlwNGJUL016aEp3eHJmVHVwUXRW
        Tjd2dnErTDhtaE5BdFpLVXBETEpCaTk3ZWRkMEk5TVZHeldSSmk1KzdBOHVra2Jp
        eVNVT0NvdW5iOVRIVlVOWjA5VDB5Y2k5d3lWSytVOXlFODBpTWNqZ3dGNGc3V1Fq
        T2NHSE9oUVhCWHo2aVJvOHYySUVxT0huTGtkQ0Y5SmYzY1dEdWZvalA1ZklDY2xD
        YmF5QUFTNmNqbWwvdDZVYU1mRU01L0dMR3cyMU03WDA4Nkl6YlJKYlFyS0VmR3V2
        ekdzcDNMNExlaDFUdXp5ZjI2TzlUanlWNVFQVG15aGo1NGVVeXFRa3BzZzBqcEVH
        MW9RV3VPWVNZSStpNDZMU2p4R3NEYnl5TExURFhVZFYyN21JY0pCM2RMMzVGYVJu
        bW9kSUpqOU95ejh1UXNQZWhQWitvNGtZUDd1QnY3dEJLQjVMeDNxd3NSTFhKTDNi
        d25IT2ltb3dseVdWUXlIcDhhUUpCTWlqMXZWZ0J1dUp6d0lBSm15WkttTmQ0K1RE
        VzhYS1l1M3d5d3FQbFNuV0czU3p5cU5xTWFpRTNva0JueTBaNVVVZHpQbVUxVWNo
        eEZwUVJJNDJLT2pkcTh3UzRVS0xoSnFMQVUvdWdPc2c4THhyQXJKRjk1dFUzMkpH
        SWJMdHhCaVNpY1IxcUpDQWFGeVJDSkR0ZTNhY3JEc01xZkNSWndWdjRHZUYrbUwr
        NW4rYmc1d21JMGY4b09oV1Zidi9xeVpXZXFsc0ZYc1p3UFdNMjBYOVlkT2NRazBG
        NlJqZEEvbFlqVzRyeWFQdDJWYTQ3dzhOK09UTkpYVEtJYmdNUjBzU1hISHdYNFNs
        K09WQ3BqblRRbnVvZStxMzN2R1FULzVIbi9KMXNsM3lCMkRBbm1NNitNSE0wbjU5
        VUtIR3dOeXZtZ2t0aUJBSVNPYW5CN0JTNjh2VUhnR2gvWm5INERmcFYvZXhaOTZ2
        NmZWOFRPQVZGeWNyWllPcHZJUW1sWlRKQm9YUHY0d0IyYWwwZGtSL2Y3MlhlN1N4
        djNRbDViQ0h4K1RHVU5lbVp0VVk0MERpVGhqUHh5aFJSOFVDTUw5ZVF6SFA5bVl1
        UFRMZFlRTzJFR2dkY1VlVHpkRE0yaGZsZDVFK3dYcHIvaTA1VmdUUXFvY3prcnUy
        YStrZlBKQjJpM2dmd0dhSzBWYk1LRzVPVDhsUWlzK3JpNXhtVU43OUtoVGFVeEts
        UVo4Y2dCcUZFNml3akgvMWoxejVCb01FNmQ3Um8zSTJyR1JLN1o4NGxHL2lqa3JZ
        QjlYLzA4emR4R05ua0o5Vm5tTkZldGIreHlXOGlHVmhja0FORVAzdW9mYnpxa1pq
        bVdweFRGcUs2ZzZOV2UzR0IrbWhrSDNBUWlyUm56Tm9CRnIwK1BQNG1QK3FmMjFN
        enVzV1JLVlJnbW5IWjlQc294bE5TbUplTlNZTWd4M2praTB0UWFvMEliMHJRLzNH
        OHJ3K0J6M0Zoc0hiZ3Z2NG1zQmZZQ1QyNTNJcmFobS9OTW9Menpjbk53S2dVWW52
        THZpcnpnU1BIMGVTcElGRHU2Q1dleU9xcVJmSmNVb05rOEs5SnNwdkxmZnRTZUhl
        MUx5MzdVU3N3T3FmMVJvYnduYU9rQWx2MzFqTlZSanFWbEF5bWNpdE5KN2xmQQpN
        eFZlaHM4bW9Ga2ErMm1MaVZlV0RkUGFrMmxaQkZZcTExSGQrR25xRmF3Ci0tLSBl
        MjFBMXo4aUU5NDIvdk9wYVhQK05BLzBnWFNJTCs1OFBNR0p3ckdXWC9NCgLvV9dA
        KUhGhEm0eNIRJ0LjKRAlG2jAiIVx30WD+f/RYAixuLZBePfdXVYD4vmSfkxbrZl6
        cW2VA/yJMYsuRnw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1q25jc4rp25dq0tpnc4vkwxr6ke6mqevjvcue3fcxv9292sxdvzzfz3n6k73rssk8zjap9c3nqtszxgaz27vm4qzlfzaampglkqf4e7h8rhqy8y09u357j5e35rsz8zxuwafuxr9rxe2qhkszal697e5tskjt0dphcctdm5c793yqpdh42uchnslllzetck9f9fdpkcgpcjfa52j7zuv40wsutgf2ad34vqy7pwzeg3nq0g248l45vsdxzprakzentq37d7p8nhft7j9tj99ccj04tqk38xclrht3pzekrhjpz66fz2q8ck36mjqsf5efz25ycgpz33ekkcvwvhasd5ruyyt8cez4prz8hk4pukd6xvmuzfezf08zngqgunzwepg5a5lj9nfhz5se565vexjz4k7tjzgzdlzyhj2a3vm8p42j3xvm4yxuk3qeh0x7756l9c7qxn5hs0wurl5ppp3z5svq68q5gtcp2vf3tux79z8225xx49enwtdj04vvcg0lgyddm3qm4ymudt7ggk9vc0n24zfewj4dceph7m9sa05vphajzrugj5y3mjy9umpshdue39n62fkmewy0zf9pd4atcfg3qd5e0dtleqq4s93d2mn589arwj3hqy5jp277pzxzvspz5kj5wcarkp6nzu2spdvjxwgvqvg2w3sw4de462u84tpgnfu6qvmrdzmafg26ewk9mj2ld02qmw2f97qex427s7tdfdk02cm9e7x5yqr9ktrn32pflc2vlunh4jayqn3atxnns3uu9u32k94eehvyjm2kxahr5yuy4yc054c2cnw4q9ensrqsqjy084r3rfzy7pjpesn3h9st397henyd5u46c434d74x0yq2f95ayjut2gte9mhffsgq3tmd2zzppatj9x6t7xcj43updyh2pg82keex90ykk9jzqlup83rd3z2fyenxxaqv9ud8ffamdfevdq843nzadn48ay0cswyt27cjepl4zprt3vfkmrdyy7y4zedrefe37fum39s8th6nk9h7ghvz8guvc7tp5c2eskly0w3ljksevvsaga4r9wgrqhrm3y8r5aq2h3cxka5knnpr8xvt5juudvqeuggd25sppz2v576rcfkpfy432ryvqj9uk6mvxzjywsxv4tahx62qjxqcxwuy9sscx48l9wtf67kax2s95latd22h0cvvgcyqkptrl7ekvcnfgnps3kst8re94sfpn7pzc74m5e3x8y480ty9j4tu5cax4xuujxt84l4s4f2h6pxn2zrh5juykjpcx3ftzfghx9w0mewxk0j4z3j8946qvqjn9wlw5jza4sa6kpcyyhlgyppnl39tyw6jgl6sj9epww4d9zyl5pwu59p0cmdhvqg54j2rvycvwcaq4qa5gqeynp83yf3awjkl3pqcfvr4gsy4d7x3sae72936za065kmwg864yx3c3pmlvhprqjl423tcshcvxtrnrza9z2znfvy0yk2rujp68wjuxxzkcs235lqp9yaqhuguanrt8xgsftdpvfg5jxvpet3qjpxz9gv3j548epx2yuqghhxqvm7hc2e782wfywhwnu5vp4emhglgnekz03p7awz0rqmmelpys2d6z7f2986zhwhacjt9pdx8ly5k4gk0r3qunsa52npm7ypq52h5s69ph3vdsupjacq6v2kx0f9x8zm3e0w0hsmwsu5z27q63985zdu3rgjcxur87wad3qyxntl45qa4dydtcayk7zna6tn307qmtwz4jhh7qz2sew5zgkdvlm4rsj0kye2uf0pmmy6tw75c90qtqytgk7sgnw845htwej8rrfa3qw7kta8j3pmhlfjka5nhq7g5sxw5u4cd98nr3rgmp6vgpcyrpkt29ufjuagkkzf5vv24svtvfy4y3luyud7uhktjvcthtrnz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T21:10:41Z"
  mac: ENC[AES256_GCM,data:6oNbTzsAujsD0In2YgF8EOS4AkFxJ7DJpFgEq4KOi21bQLnNZaDR2VHqzycwEGeUnX+8lgtdEEylHqALETJGY68vGbz3Y9EYHbQHTU4cHf8jB/Ls2CCgyrbt4zEI8f3AeeNy2mCtvMJt5gZ9hj+d5oSsxEI0N+bYZIO3dgZRrek=,iv:r1bvlmh4v6lYrWl27jgkPVrJJDpkyz/PY176Q+myXxw=,tag:UfK5jjysMvRwdoAhPT7JsA==,type:str]
  version: 3.10.2
