apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:UU1/JAQtW5/PbHZi8NCN+rvq0EF3y7MYKPQpZQG3qIhhTz+UkTTu1BSdJV6BZhYF3CAHKWs=,iv:y4L+/yyIeFvQxh59s662UO5lT3+A864bIWOHGlZ1Afo=,tag:FgeF5gPp7nqCb1hPt/d3zQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHNBaXF5T3NB
        b2FwT0hQNk5ERU1IT3ZvNkxBNm9FU2I5RDBOYmlLUkwrRlE1eXo1QTEvaW05TEtQ
        anFjbUxOUmlhZ0ZBbXZnYjA5YnNxUVhhRWQyYkdtOGdVMGdLempIV0xCVXh0cmtm
        MWNIaCtJQmtSbTlsdUlBOXpLVngrbEFSQzQ1Y3Rrc0ltc01aRE5Cd2QrR09vb2Iv
        clFaa1dXdlh3SXprUUNBb2hSWjE1UWI3ekhNNnl0a0VsRXphSGhtWE9lVXhrZUFm
        dElob0Era25FVnYycldpcjB5MUE3TkxZV0I4MGZvb0RmOXh2cExjZkFYVmhzNTNa
        VklOdXY0Y1djUTZCWWZ4aGc3T1ZYNnQ5Mk5DNWVDWXJySlNtRXNGVWx1aGFSRG8z
        K2YxTG9keUN1RStsbTFtREowZFZRUEVRTGJ2ajBiMVBTWUx4SzhONXMxVlN6M2Mv
        OGpCbU90VHBrUEh4YXZvTkZhMDlITzQrdVRLMTNYemk0QXpGUm1hMWtoTC9JNEps
        a3ZLNnoxZnI2eGRSeGNyaHZ5d3V6L3poUDV1dHo4QXE5aTQrbjJlclNjMFduSzg3
        SitLaXRidUF6dnhhVmlYZGtDS0ViTm1pYmlqSVFTY3pqbVFTR2ZGaEU3U1dQZEMx
        VmhPVCtPdHlBZjhLK2lnVklRQXRFSjhXdFZNS29iazQzWlZncnVkNFd4ZktqQlky
        Wlo2b2lzN1JsQVJwZVE3bnRkN1JoeFd1ZDRvVWhMRUJPYWdsTG01NmRKUG82aG5j
        cC8wUVlkR3J0Z05kdjZrbll3anRuMzRXTjJScVRYbDZCcnFHeFJaQ0Eya29lN0JK
        RW5XU2lXVy9vOHk2Z1Qvc1lSVTBDTDlmYWFMNzJhL2E3Lys1aUZjbmpweEZjSkoy
        OTc3WUlqVHREc3FscGhMdGdMK1dFNzduaHljSVNRakR6cTNPUzN6d2FPU1lDbDZN
        UDhZV0wyRkk4anJRQ0QxWldTUXRIWE9hNUpWc1JYYy9XVVlLSFdYTzNTbUZ2dHZE
        c0hSM25xSFBYMGozQ0hMUkkwNDVITlJPMzZmVURZcE1zd0Q2ZWp1aU9FRXhHUlpa
        c1lBUTB2aUxITU5PdjJaMXI1N1RZVTVZYVcxRmF2WkNXd3hScllhUVFqem9Hamxs
        dWdPVSsvaUtyWFV2Q3J3NVFlbXpwWndPcXpVSWxKUkIyVlZoeGxSRE44Wk4rUG5D
        clIwcFkvZkNBeGZ1SDV5Q00xUEZxSDNxNE5kRi9Ha0V2Z0NJY3dxSEtrcmcreGZV
        bmZyS2tYM0ZqL0ljOStZQ0oxeHBYcDhxaVlaeWhZMkJ2MzVVRG9YMHlFZExoS2xK
        Qi9wUFJtNFhFSXVwbHlaTFI3Wi9mczI3QldEeDJ2Y1AycXRvZUFjeFEwT2hYRUwv
        LzFOcjV5UWt6eVJpTWxYMm9IaUhtWjFZNEtMV3p2a2RnV21wc0doMW11V3k4bXQ2
        VlZPblJrbUJJRTlBaUJxaGd2RldMNmtyRHJwN3c2QTBtK3FXL3VyakdtUFQrRGVG
        eEZZZG9jcTNacHM3OGtDTGU2eFU1aDBLZTRLbC94QlNTMlJka2VBcko0OE9aZVZQ
        VEhINDFmVjMrTGpvb3FOdndrTTNidmFKN2hjUlBJRVJJNTlUdThFSHlwWXluMUNp
        K3ZVQUJ4S2k2OXJZVXZKdEpGY2JzVE1pWUZPZ1NxRE9FMlpCTEZNNmp3eTZXSUln
        dlUxLzlmVUxoVWgxSUQyT0Q3akdRaTFZblBPT1RTMURUcVVxR0RXckhJZ29zSko5
        RU5jSXhDT0Nkcm1XVWJzWnYvVFk4TVlaMm9uczd2ODZnbnZZdy9DcmJNNjZKRS9h
        QjFRZnNkVHZ2b1lpcjBBZUQ4R0xjWUFLQmJybmNxaUFHVk10a2NZdU9ocnEwUys1
        bDQ2ZzhQL0txaUhhMDViTHZWbi9VRGxTNE5RdWNFN0lEUXdTNFFaVzNzTWVmUQo1
        dWtqTmY2UHVKVE5XZnZKK2tHY0NzaWNHcGJxZzQzMlVVd1ZlSjFZY0hJCi0tLSBF
        RGJBRmdHZzRCMVpDS2ZvbXBhdFEyY1U2ZUh1bUJRNTBzazU3UHU4MzhBChqjK2IX
        ddIHoCFyIxrVi31Tj5ZSudfMecCfYuEvJH1tLEy3JvyjJrqKoIyUDq+Y6+lMS/ed
        GmhGkuX8YDHxI88=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1q25jc4rp25dq0tpnc4vkwxr6ke6mqevjvcue3fcxv9292sxdvzzfz3n6k73rssk8zjap9c3nqtszxgaz27vm4qzlfzaampglkqf4e7h8rhqy8y09u357j5e35rsz8zxuwafuxr9rxe2qhkszal697e5tskjt0dphcctdm5c793yqpdh42uchnslllzetck9f9fdpkcgpcjfa52j7zuv40wsutgf2ad34vqy7pwzeg3nq0g248l45vsdxzprakzentq37d7p8nhft7j9tj99ccj04tqk38xclrht3pzekrhjpz66fz2q8ck36mjqsf5efz25ycgpz33ekkcvwvhasd5ruyyt8cez4prz8hk4pukd6xvmuzfezf08zngqgunzwepg5a5lj9nfhz5se565vexjz4k7tjzgzdlzyhj2a3vm8p42j3xvm4yxuk3qeh0x7756l9c7qxn5hs0wurl5ppp3z5svq68q5gtcp2vf3tux79z8225xx49enwtdj04vvcg0lgyddm3qm4ymudt7ggk9vc0n24zfewj4dceph7m9sa05vphajzrugj5y3mjy9umpshdue39n62fkmewy0zf9pd4atcfg3qd5e0dtleqq4s93d2mn589arwj3hqy5jp277pzxzvspz5kj5wcarkp6nzu2spdvjxwgvqvg2w3sw4de462u84tpgnfu6qvmrdzmafg26ewk9mj2ld02qmw2f97qex427s7tdfdk02cm9e7x5yqr9ktrn32pflc2vlunh4jayqn3atxnns3uu9u32k94eehvyjm2kxahr5yuy4yc054c2cnw4q9ensrqsqjy084r3rfzy7pjpesn3h9st397henyd5u46c434d74x0yq2f95ayjut2gte9mhffsgq3tmd2zzppatj9x6t7xcj43updyh2pg82keex90ykk9jzqlup83rd3z2fyenxxaqv9ud8ffamdfevdq843nzadn48ay0cswyt27cjepl4zprt3vfkmrdyy7y4zedrefe37fum39s8th6nk9h7ghvz8guvc7tp5c2eskly0w3ljksevvsaga4r9wgrqhrm3y8r5aq2h3cxka5knnpr8xvt5juudvqeuggd25sppz2v576rcfkpfy432ryvqj9uk6mvxzjywsxv4tahx62qjxqcxwuy9sscx48l9wtf67kax2s95latd22h0cvvgcyqkptrl7ekvcnfgnps3kst8re94sfpn7pzc74m5e3x8y480ty9j4tu5cax4xuujxt84l4s4f2h6pxn2zrh5juykjpcx3ftzfghx9w0mewxk0j4z3j8946qvqjn9wlw5jza4sa6kpcyyhlgyppnl39tyw6jgl6sj9epww4d9zyl5pwu59p0cmdhvqg54j2rvycvwcaq4qa5gqeynp83yf3awjkl3pqcfvr4gsy4d7x3sae72936za065kmwg864yx3c3pmlvhprqjl423tcshcvxtrnrza9z2znfvy0yk2rujp68wjuxxzkcs235lqp9yaqhuguanrt8xgsftdpvfg5jxvpet3qjpxz9gv3j548epx2yuqghhxqvm7hc2e782wfywhwnu5vp4emhglgnekz03p7awz0rqmmelpys2d6z7f2986zhwhacjt9pdx8ly5k4gk0r3qunsa52npm7ypq52h5s69ph3vdsupjacq6v2kx0f9x8zm3e0w0hsmwsu5z27q63985zdu3rgjcxur87wad3qyxntl45qa4dydtcayk7zna6tn307qmtwz4jhh7qz2sew5zgkdvlm4rsj0kye2uf0pmmy6tw75c90qtqytgk7sgnw845htwej8rrfa3qw7kta8j3pmhlfjka5nhq7g5sxw5u4cd98nr3rgmp6vgpcyrpkt29ufjuagkkzf5vv24svtvfy4y3luyud7uhktjvcthtrnz
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T19:05:13Z"
  mac: ENC[AES256_GCM,data:gYOPFG4y9fxS+6iZsPjPN3+TPoFn2ak+W1DUxK9ccKivvhQOv7oxWNWeJ0lCzbdxmOTcnMd0ZQuhLlnhx5d3NSNY4WzN6BsOw5RQLj+EIXTdQDVNJqz0+Ff477NWM+7hWr4ARYnMhfLdj+h9zwqHMAhrNJsJg5wC+c+8nW4tt4s=,iv:+yYqNw1hxTqDwd88jyDM+TaldpQuUQG5HU6RpdtdFsQ=,tag:KHUrJx3spOaByS3fj1LGxw==,type:str]
  version: 3.13.3
