---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minijinja::functions::builtins::namespace
components:
  - ../../components/common
resources:
  - ./actions-runner-controller/ks.yaml
  - ./namespace.yaml
