---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idahobealefamily-com-production
spec:
  dnsNames:
    - idahobealefamily.com
    - "*.idahobealefamily.com"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: idahobealefamily-com-production-tls
  usages:
    - digital signature
